[package]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "devm"
version = "0.1.0"

[dependencies]
# Local crates
solvent = {path = "../../lib/h2o_rs"}
solvent-async = {path = "../../lib/h2o_async"}
solvent-fs = {path = "../../lib/h2o_fs"}
solvent-rpc = {path = "../../lib/h2o_rpc"}
solvent-std = {path = "../../lib/h2o_std"}
# External crates
futures-lite = {version = "1.12", default-features = false, features = ["alloc"]}
log = "0.4"
serde = {version = "1.0", default-features = false, features = ["derive", "alloc"]}
