[package]
edition = "2021"
name = "devm"
version = "0.1.0"

[dependencies]
# Local crates
solvent = {path = "../../lib/h2o_rs"}
solvent-async = {path = "../../lib/h2o_async"}
solvent-fs = {path = "../../lib/h2o_fs"}
solvent-rpc = {path = "../../lib/h2o_rpc"}
solvent-std = {path = "../../lib/h2o_std"}
# External crates
log = "0.4"
futures-lite = {version = "1.12", default-features = false, features = ["alloc"]}
