[build]
target = "x86_64-unknown-uefi"

[unstable]
build-std = ["core", "compiler_builtins", "alloc", "panic_abort"]
build-std-features = ["compiler-builtins-mem"]

[profile.dev]
incremental = true
lto = 'thin'
panic = 'abort'

[profile.release]
incremental = true
lto = 'thin'
opt-level = 0
panic = 'abort'
