[workspace]
members = [
  "h2o/boot",
  "h2o/kernel",
  "h2o/libs/*",
  "h2o/tinit",
  "src/bin/*",
  "src/lib/*",
  "src/lib/libc/ldso",
  "src/lib/libr/core",
  "src/lib/h2o_rpc/core",
  "src/lib/h2o_rpc/macros",
  "src/lib/h2o_rpc/gen",
  "xtask",
]

exclude = ["src/bin/.cargo"]
