[package]
name = "h2o_boot"
version = "0.1.0"
authors = ["徐启航 <akucxy@163.com>"]
edition = "2018"

[dependencies]
elf_rs = "0.1"
log = "0.4"
paging = { path = "../libs/paging" }
raw-cpuid = "9.0"
static_assertions = "1.1"
tinybmp = "0.2"
uefi = { version = "0.7", features = [ "logger", "alloc" ] }