[package]
name = "kernel"
version = "0.1.0"
authors = ["徐启航 <akucxy@163.com>"]
edition = "2018"

[lib]
name = "h2o"
path = "src/kmain.rs"
crate-type = ["staticlib"]

[dependencies]
# Local crates
archop = { path = "../libs/archop" }
paging = { path = "../libs/paging" }
# External crates
log = "0.4"
spin = "0.7"