[package]
name = "kernel"
version = "0.1.0"
authors = ["徐启航 <akucxy@163.com>"]
edition = "2018"

[lib]
name = "h2o"
path = "src/kmain.rs"
crate-type = ["staticlib"]

[dependencies]
# Local crates
archop = { path = "../libs/archop" }
canary = { path = "../libs/canary" }
collection_ex = { path = "../libs/collection_ex" }
heap = { path = "../libs/heap" }
minfo = { path = "../libs/minfo" }
paging = { path = "../libs/paging" }
pmm = { path = "../libs/pmm" }
# External crates
derive_builder = "0.9"
bitflags = "1.2"
cfg-if = "1.0"
lazy_static = { version = "1.4", features = ["spin_no_std"] }
log = "0.4"
modular-bitfield = "0.11"
spin = "0.7"
static_assertions = "1.1"