[package]
name = "kernel"
version = "0.1.0"
authors = ["徐启航 <akucxy@163.com>"]
edition = "2018"

[lib]
name = "h2o"
path = "src/kmain.rs"
crate-type = ["staticlib"]

[dependencies]
# Local crates
archop = { path = "../libs/archop" }
canary = { path = "../libs/canary" }
heap = { path = "../libs/heap" }
minfo = { path = "../libs/minfo" }
paging = { path = "../libs/paging" }
pmm = { path = "../libs/pmm" }
# External crates
bitflags = "1.2"
log = "0.4"
spin = "0.7"