[package]
name = "kernel"
version = "0.1.0"
authors = ["徐启航 <akucxy@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "h2o"
path = "src/kmain.rs"
crate-type = ["staticlib"]

[dependencies]
paging = { path = "../libs/paging" }