[package]
edition = "2021"
name = "progm"
version = "0.1.0"

[dependencies]
# Local crates
solvent-std = {path = "../../lib/libr"}
solvent = {path = "../../lib/h2o_rs"}
solvent-async = {path = "../../lib/h2o_async"}
# External crates
log = "0.4"
