[package]
edition = "2021"
name = "progm"
version = "0.1.0"

[dependencies]
# Local crates
bootfs = {path = "../../lib/bootfs"}
solvent = {path = "../../lib/h2o_rs"}
solvent-async = {path = "../../lib/h2o_async"}
solvent-rpc = {path = "../../lib/h2o_rpc"}
solvent-std = {path = "../../lib/libr"}
# External crates
log = "0.4"
