[package]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "drvhost"
version = "0.1.0"

[dependencies]
# Local crates
solvent = {path = "../../lib/h2o_rs"}
solvent-async = {path = "../../lib/h2o_async"}
solvent-ddk = {path = "../../lib/h2o_ddk", default-features = false}
solvent-fs = {path = "../../lib/h2o_fs"}
solvent-rpc = {path = "../../lib/h2o_rpc"}
solvent-std = {path = "../../lib/h2o_std"}
# External crates
async-task = {version = "4.3", default-features = false}
log = "0.4"
