[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
linker = "ld.lld"
rustflags = [
    "-Crelocation-model=pic",
    "-Clink-args=--apply-dynamic-relocs"
]

[profile.dev]
incremental = true
lto = 'thin'
panic = 'abort'

[profile.release]
incremental = true
lto = 'fat'
opt-level = 3
panic = 'abort'
