[package]
edition = "2021"
name = "tinit"
version = "0.1.0"

[lib]
crate-type = ["staticlib"]
name = "tinit"
path = "src/tmain.rs"

[dependencies]
# Local crates
heap = {path = "../libs/heap"}
solvent = {path = "../libs/syscall"}
# External crates
log = "0.4"
