[package]
edition = "2021"
name = "h2o_tinit"
version = "0.1.0"

[[bin]]
name = "tinit"
path = "src/tmain.rs"

[dependencies]
# Local crates
heap = {path = "../libs/heap"}
solvent = {path = "../libs/syscall"}
# External crates
log = "0.4"
